version: '3'

service:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "8001:8001"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8004:8004"
